#!/usr/bin/env python3

from sys import argv, stdout
from src.classes.BadArgumentRaiser import BadArgumentRaiser
from src.utils.help import helper
from src.classes.Program import Program

def main():

    try:
        if len(argv) == 2:
            if argv[1] == "-h" or argv[1] == "--help":
                helper()
            else:
                raise BadArgumentRaiser(" Are you sure you are using the correct parameters? Try -h")
        elif len(argv) == 5:
            program = Program(int(argv[1]), int(argv[2]), int(argv[3]), int(argv[4]))
            program.run()
        else:
            raise BadArgumentRaiser(" Are you sure you are using the correct parameters? Try -h")
    except SystemExit:
        exit(0)
    except BaseException as error:
        print(str(type(error).__name__) + ":{}\n".format(error) )
        exit(84)


if __name__ == "__main__":
    main()
