#!/usr/bin/env python3

##
## EPITECH PROJECT, 2021
## 204ducks
## File description:
## 204ducks
##

from sys import argv
from src.ArgHandler import ArgHandler
from src.Calculations import Calculations

def main():
    argHandler = ArgHandler()

    if (argHandler.helper(argv)):
        exit(0)
    if argHandler.checkArgs(argv) == 84:
        exit(84)
    else:
        calculations = Calculations()
        calculations.run()

if __name__ == "__main__":
    main()
