#!/usr/bin/env python3

from sys import argv
from src.Calculator import Calculator

def helper():
    print("USAGE\n"
            "\t./208dowels O0 O1 O2 O3 O4 O5 O6 O7 O8\n"
            "\n"
            "DESCRIPTION\n"
            "\tOi\tsize of the observed class")

def is_int(value):
    try:
        int(value)
    except ValueError:
        return False
    else:
        return True

def check_args(argv):

    arg_sum = 0
    if len(argv) != 10:
        return 84
    for i in range(1, len(argv)):
        if is_int(argv[i]) != True or int(argv[i]) < 0:
            return 84
        arg_sum += int(argv[i])
    if arg_sum != 100:
        return 84
    return 0

def is_help(argv):
    if "-h" in argv or "--help" in argv:
        return True
    return False

def main():
    if is_help(argv) == True:
        helper()
    elif check_args(argv) == 84:
        exit (84)
    else:
        calculator = Calculator()
        calculator.run()

if __name__ == "__main__":
    main()