#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## 207
## File description:
## 207demography
##

from src.ErrorCheck import ErrorCheck
from src.demography import Demography

def main():
    err = ErrorCheck()
    dem = Demography()

    err.errorCheck()
    dem.demography()
    exit (0)


if __name__ == "__main__":
    main()
