#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## B-MAT-400-BAR-4-1-203hotline-leon.ducasse
## File description:
## 203hotline
##

from sys import argv as av
from src.errorCheck import ErrorCheck
from src.Hotline import Hotline

def main():
    err = ErrorCheck()
    hotline = Hotline()
    hotline.hotline()
    exit(0)

if __name__ == "__main__":
    main()