#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## B-MAT-400-BAR-4-1-202unsold-leon.ducasse
## File description:
## 202unsold
##

from sys import argv as av
from src.errorCheck import ErrorCheck
from src.unsold import Unsold

def main():

    erroCheck = ErrorCheck()
    erroCheck.helper(av)
    erroCheck.checkArg(av)

    unsold = Unsold()
    unsold.separator()
    unsold.first_result()
    unsold.separator()
    unsold.second_result()
    unsold.separator()
    unsold.third_result()
    unsold.separator()
    
    exit(0)

if __name__ == "__main__":
    main()