#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## 205
## File description:
## 205IQ
##

from src.ErrorCheck import ErrorCheck
from src.IQ import IQ

def main():
    ErrorCheck()
    Iq = IQ()

    Iq.mainLoop()
    exit(0)


if __name__ == "__main__":
    main()