#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## B-MAT-400-BAR-4-1-209poll-jose-antonio.rodriguez-assalone
## File description:
## 209poll
##

from src.ErrorCheck import ErrorCheck
from src.Poll import Poll

def main():
    ErrorCheck()
    poll = Poll()

    poll.run()
    exit(0)

if __name__ == "__main__":
    main()